import { useEffect, useState, type ReactNode } from 'react';
import { Bell, CalendarDays, Check, MoreHorizontal, Plus, RefreshCw, ShieldAlert, Sparkles, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { createAppointment, createComplaint, createSubscription, loadCustomersForSelect } from '@/lib/workspace';
import type { AppNotification, Appointment, Complaint, Subscription } from '@/types';

type PageShellProps = { title: string; subtitle: string; action?: string; onAction?: () => void; children: ReactNode };
function PageShell({ title, subtitle, action, onAction, children }: PageShellProps) { return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="font-display text-2xl font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{action && <button onClick={onAction} className="primary-button"><Plus size={17} /> {action}</button>}</div>{children}</div>; }
function Empty({ text }: { text: string }) { return <div className="p-10 text-center text-sm text-slate-400">{text}</div>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/40 backdrop-blur-sm sm:items-center sm:p-4"><div className="scroll-touch flex max-h-[92vh] w-full max-w-lg flex-col overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="mb-6 flex items-center justify-between"><h3 className="font-display text-lg font-bold text-slate-900">{title}</h3><button onClick={onClose} className="icon-button"><X size={19} /></button></div>{children}</div></div>; }

export function SubscriptionsPage() {
  const [items, setItems] = useState<Subscription[]>([]); const [loading, setLoading] = useState(true); const [showNew, setShowNew] = useState(false);
  async function refresh() { setLoading(true); supabase.from('subscriptions').select('id, customer_id, name, price_usd, allowed_washes, used_washes, starts_at, expires_at, status').order('expires_at').then(({ data }) => { setItems((data ?? []) as Subscription[]); setLoading(false); }); }
  useEffect(() => { refresh(); }, []);
  return <PageShell title="Abonnements & fidélité" subtitle="Suivez les formules actives, leurs utilisations et les échéances." action="Nouvel abonnement" onAction={() => setShowNew(true)}><div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Abonnements actifs</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">{items.filter(item => item.status === 'active').length}</div></div><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Utilisations ce mois</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">{items.reduce((sum, item) => sum + item.used_washes, 0)}</div></div><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Revenus abonnements</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">${items.reduce((sum, item) => sum + Number(item.price_usd), 0).toFixed(2)}</div></div></div><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-display font-bold text-slate-900">Membres et formules</h3><p className="mt-1 text-xs text-slate-400">Données synchronisées avec votre espace</p></div><button className="icon-button"><RefreshCw size={17} /></button></div>{loading ? <Empty text="Chargement des abonnements…" /> : items.length === 0 ? <Empty text="Aucun abonnement enregistré pour le moment." /> : <div className="divide-y divide-slate-50">{items.map(item => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-50 text-cyan-700"><Sparkles size={18} /></div><div><div className="text-sm font-bold text-slate-800">{item.name}</div><div className="mt-1 text-xs text-slate-400">Client {item.customer_id.slice(0, 8)} · expire le {new Date(item.expires_at).toLocaleDateString('fr-FR')}</div></div></div><div className="text-sm font-semibold text-slate-700">${Number(item.price_usd).toFixed(2)}</div><div className="text-sm text-slate-500">{item.used_washes} / {item.allowed_washes ?? '∞'} lavages</div><span className={`badge ${item.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.status === 'active' ? 'Actif' : item.status}</span><button className="icon-button"><MoreHorizontal size={17} /></button></div>)}</div>}</div>{showNew && <NewSubscriptionModal onClose={() => setShowNew(false)} onCreated={() => { setShowNew(false); refresh(); }} />}</PageShell>;
}

function NewSubscriptionModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [customers, setCustomers] = useState<{ id: string; full_name: string }[]>([]); const [customerId, setCustomerId] = useState(''); const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [washes, setWashes] = useState(''); const [expires, setExpires] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { loadCustomersForSelect().then(setCustomers).catch(() => {}); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await createSubscription({ customer_id: customerId, name, price_usd: Number(price), allowed_washes: washes ? Number(washes) : null, expires_at: expires }); onCreated(); } catch { setError('Impossible de créer l\'abonnement.'); } finally { setSaving(false); } }
  return <Modal title="Nouvel abonnement" onClose={onClose}><form onSubmit={submit} className="space-y-4"><div><label className="label">Client</label><select className="input" value={customerId} onChange={e => setCustomerId(e.target.value)} required>{customers.map(c => <option key={c.id} value={c.id}>{c.full_name}</option>)}</select></div><div><label className="label">Nom de la formule</label><input className="input" value={name} onChange={e => setName(e.target.value)} placeholder="Ex : Pack 10 lavages" required /></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Prix USD</label><input className="input" type="number" step="0.01" value={price} onChange={e => setPrice(e.target.value)} required /></div><div><label className="label">Lavages (vide = illimité)</label><input className="input" type="number" value={washes} onChange={e => setWashes(e.target.value)} /></div></div><div><label className="label">Date d\'expiration</label><input className="input" type="date" value={expires} onChange={e => setExpires(e.target.value)} required /></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<button className="primary-button h-11 w-full" disabled={saving}><Check size={17} /> {saving ? 'Création…' : 'Créer l\'abonnement'}</button></form></Modal>;
}

export function AppointmentsPage() {
  const [items, setItems] = useState<Appointment[]>([]); const [loading, setLoading] = useState(true); const [showNew, setShowNew] = useState(false);
  async function refresh() { setLoading(true); supabase.from('appointments').select('id, customer_name, vehicle_label, service_name, starts_at, status').order('starts_at').then(({ data }) => { setItems((data ?? []) as Appointment[]); setLoading(false); }); }
  useEffect(() => { refresh(); }, []);
  return <PageShell title="Rendez-vous" subtitle="Planifiez les services longs et visualisez les créneaux de la journée." action="Nouveau rendez-vous" onAction={() => setShowNew(true)}><div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Aujourd'hui</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">{items.length}</div><div className="mt-1 text-xs text-slate-400">rendez-vous planifiés</div></div><div className="card p-5"><div className="text-xs font-semibold text-slate-400">À venir</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">{items.filter(item => item.status === 'confirmed').length}</div></div><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Postes réservés</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">{Math.min(items.length, 4)} / 4</div></div></div><div className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h3 className="font-display font-bold text-slate-900">Calendrier des arrivées</h3><p className="mt-1 text-xs text-slate-400">Les rendez-vous enregistrés dans Supabase</p></div>{loading ? <Empty text="Chargement du calendrier…" /> : items.length === 0 ? <Empty text="Aucun rendez-vous enregistré." /> : <div className="divide-y divide-slate-50">{items.map(item => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-orange-600"><CalendarDays size={19} /></div><div className="w-24 font-display text-lg font-bold text-slate-800">{new Date(item.starts_at).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })}</div><div className="flex-1"><div className="text-sm font-bold text-slate-800">{item.customer_name}</div><div className="mt-1 text-xs text-slate-400">{item.vehicle_label} · {item.service_name}</div></div><span className={`badge ${item.status === 'confirmed' ? 'bg-cyan-50 text-cyan-700' : 'bg-emerald-50 text-emerald-700'}`}>{item.status === 'confirmed' ? 'Confirmé' : item.status}</span><button className="icon-button"><MoreHorizontal size={17} /></button></div>)}</div>}</div>{showNew && <NewAppointmentModal onClose={() => setShowNew(false)} onCreated={() => { setShowNew(false); refresh(); }} />}</PageShell>;
}

function NewAppointmentModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [customer, setCustomer] = useState(''); const [vehicle, setVehicle] = useState(''); const [service, setService] = useState('Lavage complet'); const [datetime, setDatetime] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await createAppointment({ customer_name: customer || 'Client comptoir', vehicle_label: vehicle || 'Véhicule à préciser', service_name: service, starts_at: new Date(datetime).toISOString() }); onCreated(); } catch { setError('Impossible de créer le rendez-vous.'); } finally { setSaving(false); } }
  return <Modal title="Nouveau rendez-vous" onClose={onClose}><form onSubmit={submit} className="space-y-4"><div><label className="label">Client</label><input className="input" value={customer} onChange={e => setCustomer(e.target.value)} placeholder="Nom du client (optionnel)" /></div><div><label className="label">Véhicule</label><input className="input" value={vehicle} onChange={e => setVehicle(e.target.value)} placeholder="Ex : Toyota Rav4 · CG 4821 AB" /></div><div><label className="label">Service</label><select className="input" value={service} onChange={e => setService(e.target.value)}><option>Lavage extérieur</option><option>Lavage complet</option><option>Lavage premium</option><option>Nettoyage intérieur</option><option>Detailing</option></select></div><div><label className="label">Date et heure</label><input className="input" type="datetime-local" value={datetime} onChange={e => setDatetime(e.target.value)} required /></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<button className="primary-button h-11 w-full" disabled={saving}><Check size={17} /> {saving ? 'Création…' : 'Créer le rendez-vous'}</button></form></Modal>;
}

export function ComplaintsPage() {
  const [items, setItems] = useState<Complaint[]>([]); const [loading, setLoading] = useState(true); const [showNew, setShowNew] = useState(false);
  async function refresh() { setLoading(true); supabase.from('complaints').select('id, case_number, customer_name, subject, priority, status, created_at').order('created_at', { ascending: false }).then(({ data }) => { setItems((data ?? []) as Complaint[]); setLoading(false); }); }
  useEffect(() => { refresh(); }, []);
  return <PageShell title="Réclamations & qualité" subtitle="Traitez les demandes clients et gardez une trace des résolutions." action="Nouvelle réclamation" onAction={() => setShowNew(true)}><div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Dossiers ouverts</div><div className="mt-2 font-display text-2xl font-bold text-slate-900">{items.filter(item => !['resolved', 'closed', 'rejected'].includes(item.status)).length}</div></div><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Priorité urgente</div><div className="mt-2 font-display text-2xl font-bold text-rose-600">{items.filter(item => item.priority === 'urgent').length}</div></div><div className="card p-5"><div className="text-xs font-semibold text-slate-400">Résolues ce mois</div><div className="mt-2 font-display text-2xl font-bold text-emerald-600">{items.filter(item => item.status === 'resolved').length}</div></div></div><div className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h3 className="font-display font-bold text-slate-900">Suivi des dossiers</h3></div>{loading ? <Empty text="Chargement des réclamations…" /> : items.length === 0 ? <Empty text="Aucune réclamation enregistrée." /> : <div className="divide-y divide-slate-50">{items.map(item => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.priority === 'urgent' ? 'bg-rose-50 text-rose-600' : 'bg-amber-50 text-amber-600'}`}><ShieldAlert size={18} /></div><div className="flex-1"><div className="flex items-center gap-2"><span className="text-xs font-bold text-cyan-700">{item.case_number}</span><span className={`badge ${item.priority === 'urgent' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{item.priority}</span></div><div className="mt-1 text-sm font-bold text-slate-800">{item.subject}</div><div className="mt-1 text-xs text-slate-400">{item.customer_name} · {new Date(item.created_at).toLocaleDateString('fr-FR')}</div></div><span className={`badge ${item.status === 'resolved' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.status === 'resolved' ? 'Résolue' : 'À traiter'}</span><button className="icon-button"><MoreHorizontal size={17} /></button></div>)}</div>}</div>{showNew && <NewComplaintModal onClose={() => setShowNew(false)} onCreated={() => { setShowNew(false); refresh(); }} />}</PageShell>;
}

function NewComplaintModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [customer, setCustomer] = useState(''); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [priority, setPriority] = useState('normal'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await createComplaint({ customer_name: customer || 'Client comptoir', subject, description, priority }); onCreated(); } catch { setError('Impossible de créer la réclamation.'); } finally { setSaving(false); } }
  return <Modal title="Nouvelle réclamation" onClose={onClose}><form onSubmit={submit} className="space-y-4"><div><label className="label">Client</label><input className="input" value={customer} onChange={e => setCustomer(e.target.value)} placeholder="Nom du client (optionnel)" /></div><div><label className="label">Sujet</label><input className="input" value={subject} onChange={e => setSubject(e.target.value)} placeholder="Ex : Traces de savon" required /></div><div><label className="label">Description</label><textarea className="input min-h-24" value={description} onChange={e => setDescription(e.target.value)} placeholder="Détails de la réclamation" /></div><div><label className="label">Priorité</label><select className="input" value={priority} onChange={e => setPriority(e.target.value)}><option value="low">Basse</option><option value="normal">Normale</option><option value="high">Haute</option><option value="urgent">Urgente</option></select></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<button className="primary-button h-11 w-full" disabled={saving}><Check size={17} /> {saving ? 'Création…' : 'Créer la réclamation'}</button></form></Modal>;
}

export function NotificationsPage({ userId }: { userId: string }) {
  const [items, setItems] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { supabase.from('notifications').select('id, title, message, category, is_read, created_at').eq('user_id', userId).order('created_at', { ascending: false }).then(({ data }) => { setItems((data ?? []) as AppNotification[]); setLoading(false); }); }, [userId]);
  async function markRead(id: string) { const { error } = await supabase.from('notifications').update({ is_read: true }).eq('id', id); if (!error) setItems(current => current.map(item => item.id === id ? { ...item, is_read: true } : item)); }
  return <PageShell title="Notifications" subtitle="Retrouvez vos alertes opérationnelles et financières."><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-display font-bold text-slate-900">Centre d’alertes</h3><p className="mt-1 text-xs text-slate-400">{items.filter(item => !item.is_read).length} notification(s) non lue(s)</p></div><Bell size={20} className="text-cyan-700" /></div>{loading ? <Empty text="Chargement des notifications…" /> : items.length === 0 ? <Empty text="Vous êtes à jour. Aucune alerte pour le moment." /> : <div className="divide-y divide-slate-50">{items.map(item => <button key={item.id} onClick={() => markRead(item.id)} className={`flex w-full items-start gap-3 p-5 text-left transition hover:bg-slate-50 ${item.is_read ? 'opacity-60' : ''}`}><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-cyan-50 text-cyan-700"><Bell size={17} /></div><div className="flex-1"><div className="text-sm font-bold text-slate-800">{item.title}</div><div className="mt-1 text-sm leading-relaxed text-slate-500">{item.message}</div><div className="mt-2 text-xs text-slate-400">{new Date(item.created_at).toLocaleString('fr-FR')}</div></div>{item.is_read ? <Check size={17} className="text-emerald-600" /> : <span className="mt-1 h-2 w-2 rounded-full bg-cyan-600" />}</button>)}</div>}</div></PageShell>;
}
